site_name: Digi-Stammtisch Wissensseite
site_description: Ein schlankes, mitmachfreundliches Wiki für unseren Digi-Stammtisch
site_url: https://ralphmueller.github.io/digi-wissensdatenbank
theme:
  name: material
  palette: 
    primary: green
  language: de
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
plugins:
  - search
  - tags
  - glightbox
  - awesome-pages
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
extra:
  social:
    - icon: material/github
      link: https://github.com/DEIN-ORG/digi-stammtisch-wissen
      name: Repo
