
site_name: Digi-Stammtisch Wissensseite
site_description: Ein schlankes, mitmachfreundliches Wiki für unseren Digi-Stammtisch
site_url: https://ralphmueller.github.io/digi-wissensdatenbank/
theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
plugins:
  - search
  - tags
  - glightbox
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
nav:
  - Start: index.md
  - Glossar: 
      - glossar/
  - Anleitungen:
      02-anleitungen
  - Artikel:
      - Cloud verständlich: 03-artikel/cloud-verstaendlich.md
  - Über uns: about.md
extra:
  social:
    - icon: material/github
      link: https://ralphmueller.github.io/digi-wissensdatenbank/
      name: Repo